In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
import math

In [2]:
data = pd.read_csv('3D_spatial_network.csv')
data = ( data - np.mean(data, axis= 0) )/np.std(data, axis= 0)

#data.head()

   latitude  longitude  altitude
0 -0.608893  -1.184482 -0.275682
1 -0.608351  -1.185163 -0.245492
2 -0.607777  -1.185626 -0.220318
3 -0.607367  -1.185833 -0.209794
4 -0.606972  -1.185827 -0.202086

In [3]:
X=data[["latitude","longitude"]].copy()
Y=data["altitude"].values.reshape(-1,1)
X.insert(0,'1s',1)
print(X)

        1s  latitude  longitude
0        1 -0.608893  -1.184482
1        1 -0.608351  -1.185163
2        1 -0.607777  -1.185626
3        1 -0.607367  -1.185833
4        1 -0.606972  -1.185827
5        1 -0.606301  -1.185772
6        1 -0.605260  -1.185578
7        1 -0.604794  -1.185443
8        1 -0.604533  -1.185334
9        1 -0.604307  -1.185218
10       1 -0.603748  -1.184743
11       1 -0.603225  -1.184384
12       1 -0.602708  -1.184054
13       1 -0.601990  -1.183847
14       1 -0.601349  -1.183531
15       1 -0.601021  -1.183342
16       1 -0.600498  -1.183122
17       1 -0.600145  -1.183049
18       1 -0.599755  -1.183025
19       1 -1.827015  -0.252598
20       1 -1.827780  -0.254892
21       1 -1.830583  -0.258552
22       1 -1.831046  -0.259800
23       1 -1.831956  -0.262250
24       1 -1.832024  -0.262432
25       1 -1.833039  -0.265162
26       1 -1.834007  -0.267680
27       1 -1.865076  -0.209541
28       1 -1.866205  -0.210655
29       1 -1.867119  -0.210359
...     ..       ...        ...
434844   1  0.336208   1.444142
434845   1  0.336773   1.444022
434846   1  0.337269   1.443803
434847   1  0.338107   1.443325
434848   1  0.338842   1.442847
434849   1  0.339633   1.442286
434850   1  0.344703   1.459550
434851   1  0.338500   1.433632
434852   1  0.337628   1.433906
434853   1  0.331849   1.447534
434854   1  0.331642   1.445297
434855   1  0.331608   1.444839
434856   1  0.331386   1.444640
434857   1  0.331266   1.444421
434858   1  0.331198   1.443624
434859   1  0.331009   1.441553
434860   1  0.330975   1.440378
434861   1  0.330770   1.439681
434862   1  0.330308   1.438924
434863   1  0.329607   1.438347
434864   1  0.329197   1.438028
434865   1  0.328752   1.437829
434866   1  0.328324   1.437829
434867   1  0.327777   1.437790
434868   1  0.327127   1.437451
434869   1  0.326204   1.436814
434870   1  0.324955   1.435918
434871   1  0.323861   1.435420
434872   1  0.337361   1.423802
434873   1  0.337317   1.425015

[434874 rows x 3 columns]

In [4]:
x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.2,random_state=24)
train_set_size = int(data.shape[0]*80/100)
test_set_size = int(data.shape[0]*20/100)

#train_data = data[0:train_size:,:]
#test_data = data[train_size:,:]

In [5]:
size=len(x_train)
learning_rate=1e-6
max_iters=1000

In [6]:
X.insert(3,'x1^2',X['latitude']**2)
X.insert(4,'x2^2',X['longitude']**2)
X.insert(5,'x1*x2',X['latitude']*X['longitude'])
#X = ( X - np.mean(X, axis= 0) )/np.std(X, axis= 0)
print(X)

def calc_grad_2(w0,w1,w2,w3,w4,w5):
    w=np.array([w0,w1,w2,w3,w4,w5]).reshape(-1,1)
    
    dw0= np.sum(np.dot(X,w)-Y)/size
    dw1= np.sum(np.multiply((np.dot(X,w)-Y),X['latitude'].values.reshape(-1,1)))/size
    dw2= np.sum(np.multiply((np.dot(X,w)-Y),X['longitude'].values.reshape(-1,1)))/size
    dw3= np.sum(np.multiply((np.dot(X,w)-Y),X['x1^2'].values.reshape(-1,1)))/size
    dw4= np.sum(np.multiply((np.dot(X,w)-Y),X['x2^2'].values.reshape(-1,1)))/size
    dw5= np.sum(np.multiply((np.dot(X,w)-Y),X['x1*x2'].values.reshape(-1,1)))/size
      
    return dw0,dw1,dw2,dw3,dw4,dw5

        1s  latitude  longitude      x1^2      x2^2     x1*x2
0        1 -0.608893  -1.184482  0.370750  1.402998  0.721222
1        1 -0.608351  -1.185163  0.370091  1.404612  0.720995
2        1 -0.607777  -1.185626  0.369393  1.405709  0.720596
3        1 -0.607367  -1.185833  0.368895  1.406201  0.720236
4        1 -0.606972  -1.185827  0.368415  1.406186  0.719764
5        1 -0.606301  -1.185772  0.367600  1.406056  0.718934
6        1 -0.605260  -1.185578  0.366340  1.405595  0.717583
7        1 -0.604794  -1.185443  0.365775  1.405276  0.716949
8        1 -0.604533  -1.185334  0.365460  1.405017  0.716573
9        1 -0.604307  -1.185218  0.365187  1.404742  0.716235
10       1 -0.603748  -1.184743  0.364512  1.403616  0.715286
11       1 -0.603225  -1.184384  0.363881  1.402764  0.714450
12       1 -0.602708  -1.184054  0.363257  1.401985  0.713639
13       1 -0.601990  -1.183847  0.362392  1.401495  0.712664
14       1 -0.601349  -1.183531  0.361621  1.400745  0.711715
15       1 -0.601021  -1.183342  0.361226  1.400298  0.711213
16       1 -0.600498  -1.183122  0.360598  1.399778  0.710463
17       1 -0.600145  -1.183049  0.360174  1.399605  0.710001
18       1 -0.599755  -1.183025  0.359706  1.399548  0.709525
19       1 -1.827015  -0.252598  3.337982  0.063806  0.461501
20       1 -1.827780  -0.254892  3.340780  0.064970  0.465886
21       1 -1.830583  -0.258552  3.351033  0.066849  0.473302
22       1 -1.831046  -0.259800  3.352730  0.067496  0.475706
23       1 -1.831956  -0.262250  3.356064  0.068775  0.480431
24       1 -1.832024  -0.262432  3.356312  0.068870  0.480781
25       1 -1.833039  -0.265162  3.360031  0.070311  0.486052
26       1 -1.834007  -0.267680  3.363580  0.071652  0.490926
27       1 -1.865076  -0.209541  3.478508  0.043907  0.390810
28       1 -1.866205  -0.210655  3.482720  0.044376  0.393125
29       1 -1.867119  -0.210359  3.486133  0.044251  0.392766
...     ..       ...        ...       ...       ...       ...
434844   1  0.336208   1.444142  0.113036  2.085545  0.485533
434845   1  0.336773   1.444022  0.113416  2.085199  0.486307
434846   1  0.337269   1.443803  0.113750  2.084568  0.486950
434847   1  0.338107   1.443325  0.114316  2.083188  0.487998
434848   1  0.338842   1.442847  0.114814  2.081809  0.488897
434849   1  0.339633   1.442286  0.115351  2.080189  0.489848
434850   1  0.344703   1.459550  0.118820  2.130288  0.503112
434851   1  0.338500   1.433632  0.114582  2.055301  0.485284
434852   1  0.337628   1.433906  0.113993  2.056087  0.484127
434853   1  0.331849   1.447534  0.110124  2.095355  0.480363
434854   1  0.331642   1.445297  0.109986  2.088883  0.479321
434855   1  0.331608   1.444839  0.109964  2.087559  0.479120
434856   1  0.331386   1.444640  0.109817  2.086983  0.478733
434857   1  0.331266   1.444421  0.109737  2.086351  0.478487
434858   1  0.331198   1.443624  0.109692  2.084051  0.478125
434859   1  0.331009   1.441553  0.109567  2.078076  0.477168
434860   1  0.330975   1.440378  0.109545  2.074690  0.476730
434861   1  0.330770   1.439681  0.109409  2.072682  0.476203
434862   1  0.330308   1.438924  0.109104  2.070504  0.475289
434863   1  0.329607   1.438347  0.108641  2.068843  0.474090
434864   1  0.329197   1.438028  0.108370  2.067926  0.473394
434865   1  0.328752   1.437829  0.108078  2.067353  0.472689
434866   1  0.328324   1.437829  0.107797  2.067353  0.472074
434867   1  0.327777   1.437790  0.107438  2.067239  0.471275
434868   1  0.327127   1.437451  0.107012  2.066266  0.470230
434869   1  0.326204   1.436814  0.106409  2.064434  0.468694
434870   1  0.324955   1.435918  0.105596  2.061860  0.466609
434871   1  0.323861   1.435420  0.104886  2.060430  0.464876
434872   1  0.337361   1.423802  0.113812  2.027212  0.480335
434873   1  0.337317   1.425015  0.113783  2.030667  0.480682

[434874 rows x 6 columns]

In [7]:
def gradient_descent_2(w0=0,w1=0,w2=0,w3=0,w4=0,w5=0):
    for i in range(max_iters):
        dw0,dw1,dw2,dw3,dw4,dw5=calc_grad_2(w0,w1,w2,w3,w4,w5)
        w0-=(learning_rate*dw0)
        w1-=(learning_rate*dw1)
        w2-=(learning_rate*dw2)
        w3-=(learning_rate*dw3)
        w4-=(learning_rate*dw4)
        w5-=(learning_rate*dw5)
        
        if(i%100==0):
            print("The updated weights after iteration {} are w0={}, w1={}, w2={}, w3={}, w4={}, w5={}".format(i,w0,w1,w2,w3,w4,w5))
            
    return w0,w1,w2,w3,w4,w5

In [8]:
w0,w1,w2,w3,w4,w5 = gradient_descent_2(0,0,0,0,0,0)

#print(w0)

The updated weights after iteration 0 are w0=1.5926006465096704e-20, w1=5.2904398194564444e-08, w2=-1.317288846527018e-07, w3=-3.265333136615285e-07, w4=2.6732951515136374e-08, w5=-1.5496762192063888e-07
2.3979831028326823e-09

In [ ]:
rmse_calc(w0,w1,w2,w3,w4,w5)

In [9]:
#rmse calculations

def rmse_calc(w0,w1,w2,w3,w4,w5):
    rms_error = 0.0
    daya_index=0
    for data_index in range(test_set_size):

        index = train_set_size + data_index - 1
        y = data.iloc[index, 2]
        x1 = data.iloc[index, 0]
        x2 = data.iloc[index, 1]

        error = abs(y - ((w1 * x1) + (w2 * x2) + (w0)+(w3 * x1**2) + (w4 * x2**2) + (w5 * x1 *x2 )))
        rms_error += (error * error)

    rms_error /= test_set_size
    rms_error = math.sqrt(rms_error)
    print("RMS Error:", rms_error)
    return rms_error